### ISSUE TITLE
Add supporting of id-value for foreign key value during post and put.

### ISSUE THREAD

**Issue by alevshunov** [nhl/link-rest#101]
I have the structure:
**User**
* int id
* string name

**Phone**
* int id
* string value
* User user (FK by int user_id)

For add the phone I use:
```
POST .../rest/phone 
{ value: '+1234567890', user_id: 5 }
```

For get the phones I use:
```
GET .../rest/phone?filter=[{"property":"user","value":5}]
```

I would like to have ability to set the id value for the same foreign key property during  POST and PUT:
```
POST .../rest/phone 
{ value: '+1234567890', user: 5 }
```

**Comment by andrus** [comment]
As far as I am concerned,  supplying "xyz_id" in responses, and processing it in requests is Sencha adapter's hack. If we can completely retire it, I'll be happy. 

Now, using relationship name for an ID value is somewhat asymmetrical with GET:

```JSON
GET : {"id":1,"user":{"id":5}}
vs.
POST/PUT :  {"id":1,"user":5}
```

But I guess this is a reasonable shortcut. 

Comments?

**Comment by rzen** [comment]
Anton is describing a common use case in sencha. In Sencha foreign collections implemented as a filtered store. When a new model (record) added to such store, the value of FK gets stamped automatically into the model. The name of the FK property will be same as that of the filter property.

Consider this example:

	User.load(1, {
		success: function(user) {
			var phones = user.phones(function(phones) {
				var newPhone = phones.add({
					id: 100,
					value: '+3333333333'
				});

				// at this point newPhone.get('user') is set to user.getId()

				phones.sync();
			});
		}
	});

	// Full fiddle is here:
	// https://fiddle.sencha.com/#fiddle/nks

Where as in this particular example it would be trivial to do something like:

	User.load(1, {
		success: function(user) {
			var phones = user.phones(function(phones) {
				var newPhone = phones.add({
					id: 100,
					user_id: user.getId(),  // <-- this
					value: '+3333333333'
				});
				phones.sync();
			});
		}
	});

There are plenty of scenarios where its much less than convenient to do.

**Comment by andrus** [comment]
Ok , I see why I was confused initially. Sencha adapter uses “relname_id” for FK, while default LR uses just “relname" (exactly what @alevshunov  was referring to). So what we need here is changing Sencha adapter to read FK from both properties.
