### ISSUE TITLE
Support for compound IDs in LR service operations

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#109]
Moved from #50.

These operations should have overloaded versions with Map&lt;String, ?> parameter:
* com.nhl.link.rest.SelectBuilder#byId
* com.nhl.link.rest.SelectBuilder#parent
* com.nhl.link.rest.SelectBuilder#toManyParent
* com.nhl.link.rest.UpdateBuilder#id
* com.nhl.link.rest.UpdateBuilder#parent
* com.nhl.link.rest.UpdateBuilder#toManyParent
* com.nhl.link.rest.DeleteBuilder#id
* com.nhl.link.rest.DeleteBuilder#parent
* com.nhl.link.rest.DeleteBuilder#toManyParent

Then, to operate on objects identified by several attributes, client may request URLs like such:
http://whatever.com/myapp/person?name=Jack&surname=Doe
http://whatever.com/myapp/person;name=Jack;surname=Doe/friends

And backend resource may use URL dereferencing strategy to his liking, for instance standard JAX-RS mapping:
```java
@Path("person")
public class Person {
    @GET
    @Path("friends")
    public DataResponse<Person> getFriends(
            @MatrixParam("name") String name,
            @MatrixParam("surname") String surname
            @Context UriInfo uriInfo
    ) {

        Map<String, Object> ids = new HashMap<>();
        ids.put(Person.NAME_PK_COLUMN, name);
        ids.put(Person.SURNAME_PK_COLUMN, surname);

        return LinkRest.select(Person.class, config)
                .parent(Person.class, ids, Person.FRIENDS)
                .uri(uriInfo)
                .select();
    }
}
```

**Comment by andrus** [comment]
+1

**Comment by atomashpolskiy** [comment]
I'm trying to implement this for the select chain. While simple select by multiple ids works fine, there's a problem with selecting by parent that has multiple ids. 

The reason is that currently selection by parent is done by adding a qualifier, that maps child's foreign key (reverse rel) to parent's ID. That's sufficient for single ID, because we don't even need to know the foreign key column name.
Obviously this approach won't work when there are several foreign key columns, and we need to map them to values passed from REST resource (which are parent's property/column names, not child's).

The only thing I can think of right now is to perform a separate query for parent earlier in the chain. Probably you would have some better ideas?

**Comment by atomashpolskiy** [comment]
Actually I have enough info to map fks to ids (by targets columns of reverse rel), so nevermind :)
