### ISSUE TITLE
PropertyMetadataEncoder should work with primitive types

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#121]
Primitive types (boolean, byte, char, short, int, long, float, double) as well as array-of-primitive types (e.g. byte[]) should map to corresponding metadata description types:

{short, int, long, float, double} -> _number_
boolean -> _boolean_
char -> _string_ (not sure?)
byte -> ?
primitive arrays -> ?

**Comment by andrus** [comment]
+1

* char -> string is reasonable choice
* byte: I guess this is still a number.
* primitive arrays: I would skip support for those right now, with one important exception - byte[]. 

byte[] is how people usually map binary data in Cayenne (e.g. this might be an image, a PDF, etc., stored as a BLOB or VARBINARY in the DB). I wanted to support those for quite some time in the LinkRest core, with Base64 encoding. ( I am not sure how Jackson would serialize those now actually, maybe we need some tests). But if we go with Base64 for byte[] serialization, the metadata type would be string (and perhaps later we'd introduce an extra field that would provide extra information, such as content type of that string).

**Comment by atomashpolskiy** [comment]
@andrus, I checked, and Jackson already encodes byte[] as Base64.

**Comment by atomashpolskiy** [comment]
As for byte, it's stored as signed in Java, but is unsigned by common sense. Therefore interpreting byte values on client side may be a problem, I guess.
