### ISSUE TITLE
Change LrAttribute.getJavaType() to return Class object

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#137]
Currently LrAttribute.getJavaType() returns a String: literal name of the type. I believe this approach originates from using Cayenne's ObjAttribute and times when Cayenne back-end was the only option in LR. I conducted some analysis of the usage of LrAttribute's type, and it looks like we can painlessly switch to using Class objects instead.

This will help eliminate a few ugly switch(case)-like constructs (for instance see PropertyMetadataEncoder.getPropertyType or AttributeEncoderFactory.buildEncoder) and a number of usages of string literals where Class objects would be more appropriate (e.g. somewhere in the code there's "java.lang.Object" being passed to some method) and of course Class.forName calls.

As a result, the only place where mapping between literals and classes will be needed will be integration with Cayenne in com.nhl.link.rest.meta.cayenne.CayenneAwareLrDataMap (and this will be much more predictable because literals that can be returned by Cayenne are listed explicitly in TypesMapping and EntityMergeSupport utility classes).

Please correct me if I'm missing something important that obliges us to use literal names instead of classes.

---

Also I noticed that TypesMapping is used in CayenneLrDbAttribute.fakeObjAttribute and the method being used (TypesMapping.getJavaBySqlType) can return nulls. I'd suggest to check and throw an exception so that we would not accidentally have null type in some LrEntity.

Last issue that I'd like to fix is that LrEntityBuilder.addAsAttribute accepts methods with void return type to become LrAttributes (with "void" type consequently).

**Comment by andrus** [comment]
The reasoning behind String's is that we are dealing with *meta*data, which may potentially exists outside of the target Java runtime and has no access to the classes. But I agree - it is moot in case of LrAttribute. After all there's a ```Class<T> getType()``` method in LrEntity.
