### ISSUE TITLE
POST with batch update creates new records out of order

### ISSUE THREAD

**Issue by bobringer** [nhl/link-rest#146]
A POST request to an endpoint that performs a syncAndSelect() does not create records in the same order they are submitted (for auto incremented ids).

Does this actually matter?

@rzen mentioned that there was a related issue in the past that would return data out of order for that POST request, which appears to be working... but the IDs are not in order so subsequent GET requests do not return the data in that order.  See the example below:

Does this actually matter?

### Request
```
POST /person/ HTTP/1.1
Host: 127.0.0.1:8187
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: b9040f0c-6488-f542-108f-0492559cbd0a

[
    {"firstName":"Bob","lastName":"One"},
    {"firstName":"John","lastName":"Two"},
    {"firstName":"Steven","lastName":"Three"}
]
```

### Response
```
{
    "data": [
        {
            "id": 200,
            "firstName": "Bob",
            "lastName": "One"
        },
        {
            "id": 202,
            "firstName": "John",
            "lastName": "Two"
        },
        {
            "id": 201,
            "firstName": "Steven",
            "lastName": "Three"
        }
    ],
    "total": 3
}
```

**Comment by atomashpolskiy** [comment]
@bobringer, in LR the objects are processed and added to Cayenne in the same order that they appear in JSON. Concrete IDs are generated and assigned to objects by Cayenne. As far as I know, the staple of Cayenne philosophy is not to rely on IDs. If the order of objects is important, you should use explicit orderings (e.g. by date of creation). That said, this behavior also seems odd to me, but I don't think there's anything we can do about it in LR.

**Comment by bobringer** [comment]
Makes sense to me.  As I mentioned, just wanted to be sure it even mattered... and if so, I wanted to make sure this was intended behavior.
