### ISSUE TITLE
Optimizing paginated fetches

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#148]
Currently we fetch a full data list in cases when "start" and "limit" are used, and then encoder encodes the needed slice, ignoring the rest. This is inefficient for sure. If the list size is 10K or 100K, it won't be just slow, the app will crash. 

Yet we can't use Cayenne offset and limit query properties because (1) we need to produce the "total" property, so we need to know how many objects matched the entire query and (2) sometimes users are doing custom server-side filtering that affects paginated content (e.g. authorization filters). 

We just brainstormed a potential improvement to this issue. The idea is to generate a SelectQuery with "pageSize" property equal to request "limit" property if limit is in use (if no limit is set, "pageSize" would only make things worse). This would ensure that "all objects" query takes minimal memory (only ID's are fetched), and full objects will be resolved only for the slice that is going to the client.

So far so good. This should  be the default strategy (again, when "limit" is present). But we need to give users a way to turn it off per endpoint. In certain circumstances resolving data one "page" at a time may become suboptimal ... e.g. large values of "limit" or custom server-side filters that reduce the resulting list by a large factor, etc.

We don't want to introduce explicit API to SelectBuilder for what amounts to a Cayenne-specific optimization. But perhaps we can implement this as a listener that (when installed) overrides CayenneFetchStage with a custom implementation that turns of SelectQuery pagination:

```java
public class NoPaginationStrategy {

  @SelectServerParamsApplied
  public <T> ProcessingStage<SelectContext<T>, T> beforeFetch(SelectContext<T> context,
			ProcessingStage<SelectContext<T>, T> next) {
      return /* a version of CayenneFetchStage that does not paginate */;
   }
}

return LinkRest.select(E10.class, config)
    .uri(uriInfo)
    .listener(new NoPaginationStrategy())
    .select();
```

**Comment by rzen** [comment]
BTW, I ran a few tests, time to execute a `SELECT` on full compliment of columns (on the table that instigated this issue) took on the order of 2 seconds (roughly 200k records). `id` only `SELECT` executed inside .1 seconds. Adding `ORDER BY` didn't increase this time appreciably as long as appropriate indices were available.

Thanks @vitalz for bringing this issue to my attention offline.

**Comment by atomashpolskiy** [comment]
@andrus, I'd say we should split the CayenneFetchStage into two separate stages: (1) building the query and (2) the "real" CayenneFetchStage. Then we'd have an entry point for augmenting the select query, and the NoPaginationStrategy listener would be really straightforward - it would just do something like `context.getQuery().setPageSize(QueryMetadata.PAGE_SIZE_DEFAULT); return next;`. What do you say?

**Comment by andrus** [comment]
+1

**Comment by atomashpolskiy** [comment]
@andrus, sadly we still have a problem. LR is fetching all objects from the database, page by page, because `com.nhl.link.rest.encoder.ListEncoder#rewind` accesses the Cayenne paged list.

**Comment by atomashpolskiy** [comment]
Actually I don't see another way than to add some option to supress couting of total (or return the "gross" total not considering custom filters).

**Comment by andrus** [comment]
The whole rewind business seems to be needed only when a filter is present (which is a special case of in-memory filtering of to-many relationships). Can we separate two cases of ListEncoder into 2 distinct strategies - a more frequent case of no Java-side filter that works without rewinding and a special case with filter?

**Comment by atomashpolskiy** [comment]
@andrus, I'd say that the rewind business is needed primarily for custom EncoderFilters, which can be applied to root collection as well

**Comment by andrus** [comment]
True. Pagination  is not a good strategy when a client filter is involved. But we still need to find a way to avoid rewind when no filter is involved, and we can use pagination.

**Comment by atomashpolskiy** [comment]
Looking at the code, we can check if `elementEncoder` is a `FilterChainEncoder` or not. If not - we can omit the fetch and call to `willEncoder`. A temporary workaround, kind of.

**Comment by andrus** [comment]
Can we also turn off pagination in SelectQuery if we expect a filter? Resolving a *full* paginated list takes 1 + N queries (where N is the number of pages), vs. just 1 without pagination.

**Comment by atomashpolskiy** [comment]
> Can we also turn off pagination in SelectQuery if we expect a filter? Resolving a full paginated list takes 1 + N queries (where N is the number of pages), vs. just 1 without pagination.

NoPaginationStrategy does exactly that, doesn't it?

**Comment by andrus** [comment]
Yes, but can it be applied automatically when we expect a filter on the main list? Doesn't look like CayenneQUeryAssembleStage is aware of the filters:

```java
int limit = context.getEntity().getFetchLimit();
if (limit > 0) {
	query.setPageSize(limit);
}
```

**Comment by atomashpolskiy** [comment]
No, it's not. As I said the main problem is with `EncoderFilter`s

**Comment by andrus** [comment]
Filter are shared and injectable, so we can make them accessible somehow... From there I guess we'll need to call 'matches(entity)' on every filter in the chain to see if the select is filtered.

**Comment by atomashpolskiy** [comment]
@andrus, check out my commit and confirm, please (checked that it works)

**Comment by andrus** [comment]
@atomashpolskiy I think we need to improve this code:

```java
 	public ListEncoder(Encoder elementEncoder) {
 		this.elementEncoder = elementEncoder;
 		this.orderings = Collections.emptyList();
+		shouldFilter = elementEncoder instanceof FilterChainEncoder;
 	}
```
"instanceof" check looks unreliable (what if we create other types of encoders in the future?). CayenneQueryAssembleStage.shouldFilter is a cleaner implementation. Perhaps we need to precalculate this flag once per request and store it in the SelectContext, and access from both places?

**Comment by atomashpolskiy** [comment]
@andrus , sure, but where? ResourceEntity must be complete at the time we calculate 'shouldFilter'. Also what if we eventually come back to this issue for the nested collections? One flag is not enough in such case. 'instanceof' is an arguable construct, but at least it's not confusing and works for all collections. Can be replaced with some explicit Encoder.isFiltering flag or something...

**Comment by andrus** [comment]
ResourceEntity is itself a nested construct, so it can potentially work for both root and child collections. So maybe that's the place? What I am also trying to avoid is implementing the same logic in 2 places.
