### ISSUE TITLE
link-rest Validation and Cayenne Listeners

### ISSUE THREAD

**Issue by rbugajewski** [nhl/link-rest#150]
Let’s assume that I have a generic `POST` request:

```
@POST
@Consumes(MediaType.APPLICATION_JSON)
public SimpleResponse createObject(String data) {
    return LinkRest.create(GenericObject.class, config).sync(data);
}
```

`GenericObject` has the property `name` and also a Cayenne listener that allows only the server to update its `createdAt` property:

```
public class CreateListener {
    @PrePersist(entityAnnotations = Timestampable.class)
    void prePersist(Persistent object) {
        DataObject dataObject = (DataObject) object;

        dataObject.writeProperty("createdAt", new Date());
    }
}
```

1. I want to ensure that there are no rows in the table with empty `createdAt` fields.
2. In the best-case scenario link-rest would “know” about my listeners (I assume this is not possible).

I have the feeling that my architecture is wrong. How can I ensure that Cayenne persists every `GenericObject` with a `createdAt` property that can only be set by the server? How can I ensure that link-rest validates just after the internal `new Date()` generation?

**Comment by andrus** [comment]
LinkRest does not validate objects. Cayenne does. Try changing @PrePersist to @PostAdd . IIRC @PrePersist is called after Cayenne commit validation.

**Comment by rbugajewski** [comment]
Thanks, this solved my issue. Now I have another one, but I will move it to the user group, because it doesn’t belong here.
