### ISSUE TITLE
Add JSON Converters for Java 8 Dates

### ISSUE THREAD

**Issue by rbugajewski** [nhl/link-rest#154]
Cayenne 4.0M3 supports Joda & Java 8 dates as modules. AFAIR LinkRest supports Joda, but not Java 8 dates. Please consider this a feature request for native Java 8 date support.

**Comment by andrus** [comment]
Coincidentally we discussed it with @thinline72 earlier today Will add it soon.

**Comment by andrus** [comment]
Usage instructions:

Import an extra module:
```xml
<dependency>
	<artifactId>link-rest-java8</artifactId>
	<groupId>com.nhl.link.rest</groupId>
	<version>1.23</version>
</dependency>
```
and then add a ```com.nhl.link.rest.runtime.adapter.java8.Java8Adapter``` to LinkRest runtime.
