### ISSUE TITLE
Not enough diagnostics on misconfigured listeners

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#157]
Had a case when a listener method wasn't public. It was quietly ignored by LinkRest. We either need an exception or a warning method here. Current behavior is confusing.

```java
@SelectServerParamsApplied
ProcessingStage<SelectContext<Session>, Session> createSession(SelectContext<Session> context,
		ProcessingStage<SelectContext<Session>, Session> next) {
...
}
```

**Comment by atomashpolskiy** [comment]
@andrus , switched to using `Class.getDeclaredMethods()`. I hope nobody uses inherited listeners.

**Comment by andrus** [comment]
All the listener annotations are ```@Inherited``` , so we make an explicit promise that interited methods will be invoked. Reopening.

**Comment by atomashpolskiy** [comment]
@andrus , according to the [JavaDoc](http://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Inherited.html) `@Inherited` can be applied only to classes:

> Note that this meta-annotation type has no effect if the annotated type is used to annotate anything other than a class.

Your point still stands I guess, I'll try to also inspect superclass's method.
