### ISSUE TITLE
ListEncoder should use elementEncoder.willEncode

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#160]
@andrus , shouldn't the ListEncoder (previously RootListEncoder) also check if elementEncoder.willEncode returns `true` in `com.nhl.link.rest.encoder.ListEncoder#encode`?

```java
private void encode(Counter c, List<?> objects, int limit, JsonGenerator out) throws IOException {

	int length = objects.size();

	for (; c.position < length && c.encoded < limit; c.position++) {

		Object o = objects.get(c.position);
		if (filter == null || filter.match(o)) {
			if (elementEncoder.encode(null, objects.get(c.position), out)) {
				c.encoded++;
			}
		}
	}
}
```

I've stumbled across this while trying to use a custom EncoderFilter to filter the root collection in the response.

**Comment by atomashpolskiy** [comment]
And also another question: should any given encoder check its `willEncode` when `encode` is called on it? I'm talking about the general convention here

**Comment by andrus** [comment]
"willEncode" return value is equivalent to "encode" return value for a given encoder or filter. So no need to check "willEncode" if we are ok with calling "encode" in a given place in the code.

**Comment by atomashpolskiy** [comment]
Thanks, @andrus !
