### ISSUE TITLE
Redefining public ID attribute

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#163]
Sometimes REST APIs may want to hide a DB-generated key from the view in favor of some unique natural key understood by the user. Would be great to support this in LinkRest. LR would do a seamless translation between visible ID and internal record ID. 

Per #164 , ```@LrId``` annotation will be recognized on persistent entities. So perhaps we'll use that to define alt. ID:

```java
public MyEntity extends _MyEntity {

    @LrId
    public String getAltId() {
       return super.getAltId();
    }
}
```

After that we will need to cover the following use cases:

* Builders fetching/modifying objects by ID should recognize public ID.
* Update requests with natural IDs need to be translated properly.
* Responses should include public ID for the "id" column.

**Comment by atomashpolskiy** [comment]
@andrus , probably should add that this user ID must be unique. We can't force it's uniqueness however (esp. in case of pojos), but we can and should:
- throw an exception when `select`/`update`/`delete` by "id" discovers several objects 
- add a check in `create` for existing objects in com.nhl.link.rest.runtime.cayenne.processor.BaseCayenneUpdateStage#createSingle (there is some magic going on already)

Also it would be nice to log a warning that the corresponding DB attribute is not unique when parsing a Cayenne entity class, but it seems like this information is not available via Cayenne's API (?)

**Comment by andrus** [comment]
Yeah, good point. And you are correct - we don't store information on column uniqueness in the Cayenne model.
