### ISSUE TITLE
Support compound IDs in Create/Update JSON payload

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#170]
Currently only scalar ID is supported -- it should be specified in `id` attribute of the JSON payload. If the entity being created/updated has a compound ID, then it should be possible for the `id` attribute to contain an object with a child node for each part of the compound ID.

E.g. if the entity `E` has compound ID `id1`, `id2`, then the payload will look like this:
```
{
    "id": {
        "id1": 1,
        "id2": 1
    },
    ...
}
```

**Comment by andrus** [comment]
I applied the part of combined pull request related to #170 , with a bit of refactoring. Still need to port the tests.
