### ISSUE TITLE
Support for "mapBy" at the top level of request

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#182]
No reason for us not to support "mapBy" key for the top level entity. Currently it is only supported inside includes. DataResponse in this case will be a map instead of a list:

```
GET /x?mapBy=key
```

```json
{
  "total" : 5,
  "data" : {
    "key1" : [ .. ],
    "key2" : [ .. ] 
}
```
I guess the meaning of "total" will be preserved to be a flat map over the result (the total number of objects across all map keys) ?

**Comment by rzen** [comment]
Keep in mind that `mapBy` key breaks compatibility with current syntax (which would be okay) but also potentially in conflict with future syntax for aggregations. Might want to think about keep object `include` syntax.

**Comment by andrus** [comment]
I don't think it does. We have precedents (cayennExp, etc) and this is how LR protocol is generally organized - at the top level you can use query parameters, and when you descend into relationships, you use the same keys within the include.

**Comment by rzen** [comment]
You are right, of course.
