### ISSUE TITLE
Metadata request: related entity type is NULL for POJO related entities

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#184]
I have a model where a root entity (Game) is persistent ,and has a relationship to a non-persistent entity (GameEvent), that is of course annotated and is present in LR model. In a metadata response this relationship has null "type":

```json
{
"name": "events",
"type": null,
"relationship": true,
"collection": true
}
```

**Comment by atomashpolskiy** [comment]
I guess that the problem lies in `com.nhl.link.rest.encoder.PropertyMetadataEncoder#getPropertyType`. We should probably replace
```java
else if (property instanceof LrPersistentRelationship) {
   return ((LrPersistentRelationship) property).getObjRelationship().getTargetEntityName();
}
```
with
```java
else if (property instanceof LrRelationship) {
    return ((LrRelationship)property).getTargetEntityType().getName(); // or getSimpleName() ?
}
```

**Comment by andrus** [comment]
Sounds about right.
