### ISSUE TITLE
Store information about the target entity in LrRelationship

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#185]
Add new method `LrEntity<?> getTargetEntity()` for `LrRelationship` and update the model's compilation stage accordingly. This new info should make the LR model more informative and useful, as well as help to fix #184

**Comment by andrus** [comment]
This is a very cool change. See how much garbage we were able to remove ([d04a713](https://github.com/nhl/link-rest/commit/d04a713f922f8409de4ff7dcd4642561757e74a7))
