### ISSUE TITLE
Sencha adapter "filter" key can't use "id" property

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#202]
Matching against "id" property works (as it should) for "cayenneExp" protocol key. E.g.:
```
target("/e2").queryParam("include", "id")
   .queryParam("cayenneExp", urlEnc("{\"exp\":\"id in (2,3)\"}")).request().get();
```
An equivalent query using Sencha Adapter "filter" key blows up with Cayenne error (as "id" property leaks down to Cayenne) : 

```
filter=[{"exactMatch":true,"disabled":false,"property":"id","operator":"in","value":[73,77,128,129]}]
```

```CayenneRuntimeException [v.4.0.M3.28c7db9 Oct 23 2015 16:20:54] Can't resolve path component: [MyEntity.id].```

So we need to port ```ExpressionPostProcessor``` inner class located in ```CayenneExpProcessorWorker``` to the Sencha adapter, to do property cleansing.

**Comment by andrus** [comment]
PR is applied. While we can have more enhancements to this implementation, the bug is fixed. So closing.

**Comment by andrus** [comment]
@atomashpolskiy : can we add a unit test with Sencha adapter using a filter matching on id? Doesn't look like we have such test (or do we?)

**Comment by atomashpolskiy** [comment]
@andrus , yes, I added such test in 006b987

**Comment by andrus** [comment]
Great thanks. Will start merging it once Travis finishes a CI build
