### ISSUE TITLE
Immutable constraint objects

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#214]
For whatever historical reason we pass a mutable ConstraintsBuilder to the SelectBuilder chain: 

```java
SelectBuilder<T> constraints(ConstraintsBuilder<T> constraints);
```

The makes the API unclear - can we reuse the ConstraintsBuilder object? Will it be modified by the caller? At the minimum we need to change this API to take `Constraint` interface which has no mutator methods. Or even better - instead of ConstraintsBuilder implementing Contraint, it can have a method that returns an immutable Constraint.

Additionally we can make `ConstraintsBuilder` itself immutable, creating a new copy for each state change.. This has an advantage of reusability when building different flavors of the same constraint.

**Comment by atomashpolskiy** [comment]
Somewhat funny, but I recall that per #176 you specifically added `LinkRestClient#include(IncludeBuilder)` method. The intent as far as I remember was to relief users from mundane calls to `build()`. I believe I've also seen this approach being used in some of the Cayenne query APIs. Just saying :)

**Comment by andrus** [comment]
With `ConstraintsBuilder` I am running into issues with reusability. Constraints are metadata trees. The ability to reuse individual subtrees (with customization) across different constraints is essential. So immutability is essential.

Yeah, we've implemented a few shortcuts in LR and Bootique passing builder to consumers  for the reasons that you mentioned. It is pretty dirty. Perhaps we need to address that too.

But aside from those cases, our typical rule of thumb was "a mutable builder (returning `this` on each call) that creates an immutable object". So here I am thinking of trying another rule - "immutable builder that is itself an object". 

I will work on this task myself. I'd like to play with the API to see what works best in apps with lots of constraints.

**Comment by andrus** [comment]
`ConstraintsBuilder` static factory methods were moved (with deprecation) to `Constraint` interface. It is advisable to
clean up all deprecation warnings.

The only subltly breaking change is that `ConstraintsBuilder` was made immutable, so whenever you are calling one of 
its builder methods, a new instance is created. So make sure you do not keep references to the intermediate builder 
results (unless this is intentional), and only use the ConstraintsBuilder instance returned from the last builder method. 
E.g. the following likely won't do what you'd expect:

```java
ConstraintsBuilder<E> c = Constraint.excludeAll();
c.attribute("a");

// Likely a bug!! "c" does not include attribute "a"
LinkRest.select(MyType.class, config).constraint(c);
```

while this will:

```java
ConstraintsBuilder<E> c = Constraint.excludeAll().attribute("a");
LinkRest.select(MyType.class, config).constraint(c);
```
