### ISSUE TITLE
Support multi-component paths for root "mapBy"

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#220]
Per #182 we started supporting "mapBy" key applied to the root result collection. However it appears that it only supports simple attribute paths (e.g. "someProp"), but not relationship paths (e.g. "someRel.someProp"). This is different from "mapBy" applied to nested paths. E.g. for this code:

```java
target("/e3").queryParam("mapBy", "e2.id")
				.queryParam("include", E3.NAME.getName()).request().get();
```

I get the following log entry:

```
[main] INFO RequestParser - Ignoring top-level 'mapBy:e2.id' -- not an attribute
```
and the returned result is our regular flat array.

@atomashpolskiy

**Comment by atomashpolskiy** [comment]
Fixed in master
