### ISSUE TITLE
POST and PUT methods doesn't supports content type header with charset

### ISSUE THREAD

**Issue by alevshunov** [nhl/link-rest#229]
`curl 'http://127.0.0.1:10000/.../rest/entity' -H 'Host: 127.0.0.1:10000' -H 'Content-Type: application/json'  --data '...'` - works well.

After adding charset to the header, like: `curl 'http://127.0.0.1:10000/.../rest/entity' -H 'Host: 127.0.0.1:10000' -H 'Content-Type: application/json; charset=UTF-8'  --data '...'` - linkrest starts to throws:
> No suitable constructor found for type [simple type, class com.nhl.link.rest.EntityUpdate<...>]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)

[MDN: Content-Type](https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Type)
[rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

**Comment by atomashpolskiy** [comment]
I've updated message body readers to ignore media type's charset.
