### ISSUE TITLE
Generic object API and type conversion problems 

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#230]
Here as scenario that we encountered in a real app:

1. Given: a model that has an entity with Float attribute
2. When the entity is updated via LinkRest, a value like 0.1234567 is parsed as Double.
3. Since LR (BaseCayenneUpdateStage) writes values to objects using DataObject.writeProperty(..), no type checking is performed. So the value is set, update is committed and the object (or rather its snapshot) ends up in a shared cache, with Double value
4. Some other ObjectContext fetches the object using Cayenne.objectForPK. The object is created, but when the property in question is accessed, a ClassCastException is thrown.

So looks like we need more strict type checking / conversion when loading updates.

**Comment by atomashpolskiy** [comment]
Seems like we need a FloatConverter in com.nhl.link.rest.runtime.parser.converter.DefaultJsonValueConverterFactory

**Comment by andrus** [comment]
Ah cool. So we already got the needed extension point.

**Comment by atomashpolskiy** [comment]
Committed the fix, please check it out
