### ISSUE TITLE
Allow Pojo attributes of type java.util.Collection

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#235]
`LrEntityBuilder` restricts attributes of type `java.util.Collection`. I believe we can remove this restriction now, as such attributes get encoded by `GenericEncoder` just fine. @andrus , do you have any objections?

**Comment by atomashpolskiy** [comment]
Changed LrEntityBuilder to support attributes with the following types:
- container should be assignable from java.util.Collection
- element should be assignable from one of: String, Number, Boolean, Character
Now have to write some tests for compiling and encoding.

(note that new rules are not applicable to ID attributes, they still can't be a Collection!)

**Comment by atomashpolskiy** [comment]
It would also be nice to support other "standard" LR attribute types as well: date/time, binary arrays... But in that case we would not be able to rely on GenericEncoder and would need to update the encoder setup.

**Comment by andrus** [comment]
I applied the PR, but as you said, perhaps we need to go a bit deeper and treat collection elements as first class citizens in LR (e.g. assign them specific encoders).

Perhaps we need a new meta object - `LrValue`. So in addition to `LrRelationship of LrEntity` we might have `LrRelationship of LrValue`?
