### ISSUE TITLE
Stop rendering timezone for all date/time values

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#275]
_Changing the default description of this task to summarize the outcome of the discussion in this issue (leaving the initial description quoted below)._ 

We need to fix timezone handling in LinkRest. All the value types that we support so far are **local** (java.util.Date, LocalDateTime, LocalDate, LocalTime, etc). Rendering them as ISO8601 strings **with timezone** is misleading. So the TZ part should not be included in String-encoded values of GET responses. Same goes for the opposite operation - decoding them from JSON coming via PUT and POST requests. 

Datetime components that have an explicit notion of TZ should be modeled in Java as such. And we'll deal with it separately per #276 .

## Upgrade Notes

For backwards compatibility there will be an optional auto-loadable module `link-rest-legacy-date-encoders` so that apps could upgrade to the new LR without breaking all their clients.

> One of our clients wants to have a configuration option to set the default timezone for the LR stack. It's intended to be used in JsonValueConverters, when receiving a date-time without timezone from the client. Per ISO8601, if the timezone is not specified, then the date-time should be considered to be in the local timezone. So they want to override the server's system default timezone with a custom timezone for LR purposes.
> 
> We'll probably need to add an option in the LR builder and figure out how to adjust date converters to make use of it. `com.nhl.link.rest.parser.converter.UtcDateConverter` seems to be simple (it directly sets the timezone in the resulting object after having parsed the textual representation). It's going to be trickier with Java 8 "local" date-time converters, because they rely on standard parsing methods (like `java.time.LocalDateTime#parse(java.lang.CharSequence)`). So we'll need to append the custom timezone to the date string before calling the `parse()` method (or come up with something more clever).
> 
> @andrus , what are your thoughts?

**Comment by atomashpolskiy** [comment]
I also found [a related discussion](https://github.com/moment/moment/issues/1167) in moment.js repo, see the third comment from below:
```
There is a bit of a mismatch because ISO8601 implies that any time that doesn't have a Z or an offset like -04:00 is to be treated as local time. While ECMA-262 (ES5) says that it should be treated as UTC if absent.
```

**Comment by rzen** [comment]
Yep, basically we're looking for an option to be able to have LR pass through date/time untranslated, sans any timezone designation. Mimic the spirit of Java8 [LocalDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html) type.

**Comment by rzen** [comment]
To follow up on the quoted comment above, it brings up an important if annoying point. 

Contrary to the comment, [ECMA-262](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-date-objects) does in fact prescribe that TZ-free date-time values to be interpreted as local time. So we're good there.

However, the comment is correct in that _date-only_ values ECMA-262 prescribes to be interpreted as UTC. Which is weird.

This is what ECMA-262 says, exactly:

> When the time zone offset is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as a local time.

Which checks out in current Chrome:

<img width="564" alt="date-time vs date only tz" src="https://user-images.githubusercontent.com/137981/32078656-b485c668-ba75-11e7-9acb-43b9d7d21e89.png">

Something to keep in mind.

**Comment by rzen** [comment]
And if that wasnt enough not all browsers follow the spec. E.g. Safari interprets TZ-free date-time as UTC..

Couple of relevant links on the topic:

https://bugs.chromium.org/p/v8/issues/detail?id=4242
https://codereview.chromium.org/2648603002/
https://chromium.googlesource.com/v8/v8/+/d31c5410c4fdfc5eb66582892d5e3ecd3706bd58

Bottom line client-side code will have to account for browser specifics even with this LR fix..

**Comment by atomashpolskiy** [comment]
> Contrary to the comment, ECMA-262 does in fact prescribe that TZ-free date-time values to be interpreted as local time. So we're good there.

This an interesting observation. In fact the comment stands correct until the 7th edition, which was released in June 2016. In 6th edition and previously it was saying simply:
> If the time zone offset is absent, the date-time is interpreted as a local time.

**Comment by andrus** [comment]
So aside from client-side specifics, on the LR end we need to respect the distinction in the model between local Date/Time and Date/Time with timezone, which should be easy with Java 8 time classes. JSON serialization and deserialization should respect it.

May have to add a backwards-compatibility layer (e.g. deserialization of local time may need to be able to parse Strings with TZ).

**Comment by atomashpolskiy** [comment]
@andrus , not sure if I understand. We already respect all possible textual formats and interpret them precisely according to ISO8601 requirements. **rzen**'s idea was (effectively) to let the user _change_ these requirements (i.e. interpret date-time string without TZ as being in UTC+0 or some other arbitrary TZ to not rely on the system default TZ).

**Comment by atomashpolskiy** [comment]
After discussion, we decided, that we need to change the ISODateEncoder (which handles encoding of java.util and java.sql date-time types) to NOT specify the TZ. This is a breaking change in protocol, so we'll also need a way for the users to switch to the old behavior. Good solution would be to have an extra Maven module, that will force usage of the old encoder (this will require refactoring AttributeEncoderFactory to support overrides).

**Comment by atomashpolskiy** [comment]
Another breaking change (unrelated to the original issue) is to remove the following code from AttributeEncoderFactory. Backwards-compatibility module should take care of this as well:
```java
if (UTIL_DATE.equals(javaType)) {
	if (jdbcType == Types.DATE) {
		return ISODateEncoder.encoder();
	}
	if (jdbcType == Types.TIME) {
		return ISOTimeEncoder.encoder();
	} else {
		// JDBC TIMESTAMP or something entirely unrecognized
		return ISODateTimeEncoder.encoder();
	}
}
```

**Comment by atomashpolskiy** [comment]
Also need to update the `JSON -> java.util/java.sql` parser to not alter the date, when the TZ is not specified by the client, and the server's TZ is different from the client's (currently the parser assumes the date to be in the server's local TZ as required by ISO).

**Comment by rzen** [comment]
@andrus not sure I followed your point but as I understand what we're doing here, there's no need to ignore TZ, all this request really means on input when TZ is missing, interpret it per ISO8601 as server local time. On output serialize in server TZ and omit the TZ.

**Comment by atomashpolskiy** [comment]
@andrus , @rzen ,

I've updated the encoders. You may take a look at the test, if you'd like: [ISOEncoderTest](https://github.com/nhl/link-rest/blob/%23275/link-rest/src/test/java/com/nhl/link/rest/runtime/encoder/ISOEncoderTest.java). 

There is a bit of javadoc for each test, I'll sum it all up here, so that we agree (or disagree), that this is how we want it to work:
- `java.util.Date` and `java.sql.Timestamp` attributes are encoded as `yyyy-MM-dd'T'HH:mm:ss[.SSS]` in server's default TZ, regardless of their JDBC type (SQL column type); fractional seconds (millis) are printed only when present in the date object;
- `java.sql.Date` attributes are encoded as `yyyy-MM-dd` in server's default TZ;
- `java.sql.Time` attributes are encoded as `HH:mm:ss[.SSS]` in server's default TZ; fractional seconds (millis) are printed only when present in the date object;

I.e., comparing with prior LR versions, the changes are:
- everything is formatted in server's default TZ
- TZ is not specified anywhere
- time is not truncated to seconds, so a fractional part may appear in the formatted string

**Comment by atomashpolskiy** [comment]
I've also checked the converters..

Parsing text into `java.util.Date` and its' `java.sql` subtypes works as intended (no conversions take place; if TZ is not specified, then server's default TZ is assumed).

Parsing text into Java 8 _local_ time, however, currently is **unable to handle TZ offsets**. @andrus , please confirm, that we'd like to support such conversions (i.e. allowing input like `2017-01-01T10:00:00+03:00` for `java.time.LocalTime` and `java.time.LocalDateTime` attributes and converting it to server's local date-time).

**Comment by andrus** [comment]
> regardless of their JDBC type

Yep, JDBC type should have no effect on Java object to JSON encoding. Places where it does should be considered legacy and scheduled for deprecation.

> everything is formatted in server's default TZ

Would it be possible to create a separate (deprecated) LR module with the old encoding strategy for backwards compatibility with JS clients as we discussed.

> Parsing text into Java 8 local time, however, currently is unable to handle TZ offsets. @andrus , please confirm, that we'd like to support such conversions (i.e. allowing input like 2017-01-01T10:00:00+03:00 for java.time.LocalTime and java.time.LocalDateTime attributes and converting it to server's local date-time).

I say we don't care at least initially.

**Comment by atomashpolskiy** [comment]
Yeah, I remember about the module

**Comment by atomashpolskiy** [comment]
What about the fractional seconds? Do you have any objections? I also plan to update java 8 encoders to print fractional part as well, so that everything would be consistent. There will be 3 different possible formats, depending on the circumstances: .SSS (millis), .SSSSSS (microseconds), .SSSSSSSSS (nanos).

**Comment by andrus** [comment]
> What about the fractional seconds? Do you have any objections?

I haven't formed opinion. So I guess this means no objections :)

**Comment by andrus** [comment]
I just merged the PR #277 with a few small changes. 

@atomashpolskiy can we please update the [UPGRADE-NOTES](https://github.com/nhl/link-rest/blob/master/UPGRADE-NOTES.md) file with an explanation on how to deal with backwards compat issues in 2.11?

**Comment by atomashpolskiy** [comment]
Sure

2017-11-04 15:00 GMT+03:00 Andrus Adamchik <notifications@github.com>:

**Comment by andrus** [comment]
Also `ISOEncoderTest` is essentially testing `EncoderService`. I suggest creating separate tests for each encoder that do not rely on `EncoderService`, and either remove the current `ISOEncoderTest` or rename it to reflect that it is testing date encoding in the context of `EncoderService`.

**Comment by atomashpolskiy** [comment]
Huh, I just found a few more classes, that presumably perform encoding of mapBy keys:
- [com.nhl.link.rest.encoder.converter](https://github.com/nhl/link-rest/tree/master/link-rest/src/main/java/com/nhl/link/rest/encoder/converter) package
- [com.nhl.link.rest.runtime.encoder.IStringConverterFactory](https://github.com/nhl/link-rest/blob/master/link-rest/src/main/java/com/nhl/link/rest/runtime/encoder/IStringConverterFactory.java)

All of these seem to mirror the JSON value converters, and now that the converters are typed, it probably makes sense to remove them completely.

**Comment by andrus** [comment]
`StringConverter` is the opposite of `JsonValueConverter` (we need better terminology for converters and encoders to avoid confusion... ValueEncoder/ValueDecoder?). It is closer to an Encoder (and is used from within encoders). It is a special encoder strategy that generates String JSON keys. Not sure how we can remove those. Perhaps we can refactor the encoders to use StringConverters internally for *values*.

**Comment by atomashpolskiy** [comment]
> Also ISOEncoderTest is essentially testing EncoderService. I suggest creating separate tests for each encoder that do not rely on EncoderService, and either remove the current ISOEncoderTest or rename it to reflect that it is testing date encoding in the context of EncoderService.

I think that we still need the encoder service test, because it verifies that the encoders are selected correctly for different attributes. But yeah, let's add a couple of simple tests for individual encoders.

**Comment by atomashpolskiy** [comment]
By the way, `Stop rendering or reading timezone for *local* date/time values` is a bit misleading: we've never allowed the client to pass timezone for local date/time attributes. So basically this should rather be `Stop rendering timezone for all date/time values`. I'll update the release notes

**Comment by rzen** [comment]
FWIW I'm in agreement with newest title of this issue, specifically `«Stop rendering timezone for all date/time values»`.

**Comment by andrus** [comment]
I am in agreement with the title change. Also I think we are finished with this issue. Closing.

**Comment by atomashpolskiy** [comment]
I'm afraid there's one thing left: string converters (switch to using new encoders internally)

**Comment by andrus** [comment]
You are right. Reopening.
