### ISSUE TITLE
Loosing capability to inject objects from other DIs with deprecation of adapters

### ISSUE THREAD

**Issue by aveprev** [nhl/link-rest#281]
With depreciation of `LinkRestAdapter` and introduction of `LrModuleProvider` an easy way to inject object managed by other DIs is lost. It is not possible to inject objects into a `LrModuleProvider` implementation since `ServiceLoader` is used to instantiate it. 

For example in the following code there is no simple way to inject `aServiceToinject` into `AFilter` using `LrModuleProvider` approach:

```java

        @Override
	public void configure(Binder binder) {
               binder.bind(IService.class).to(ServiceImpl.class);
               LinkRestModule.extend(binder).addAdapter(AnAdapter.class);
        }

        public static class AnAdapter implements LinkRestAdapter {
		private IService aServiceToinject;

		@Inject
		public LrSecurityAdapter(IService aServiceToInject) {
			this.aServiceToInject = aServiceToInject;
		}

		@Override
		public void contributeToRuntime(org.apache.cayenne.di.Binder binder) {
			binder.bind(IService.class).toInstance(aServiceToinject);
			binder.bindList(EncoderFilter.class).add(AFilter.class);
		}

		@Override
		public void contributeToJaxRs(Collection<Feature> features) {
		}
	}
```

**Comment by andrus** [comment]
Ok, this is a `bootique-linkrest` limitation... `LrModuleProvider` can be auto-loaded, but can also be passed directly to LinkRestBuilder. Just need to add Bootique extender for it. I just opened a task in Bootique : https://github.com/bootique/bootique-linkrest/issues/26
