### ISSUE TITLE
Implement explicit processing of query parameters without uriInfo.

### ISSUE THREAD

**Issue by vyarmolovich** [nhl/link-rest#296]

**Comment by andrus** [comment]
applied #297 with a few minor tweaks (https://github.com/nhl/link-rest/commit/5ee996314f88eb3992876b106685b262aa85ecdc, https://github.com/nhl/link-rest/commit/b6252c4692bf60366bfe90d7bccad6e0ab760c86). 

I am going to polish this a bit more now:

* `queryParams` and `uriInfo` in the context are redundant. So will need to merge them together at the builder level (perhaps even breaking `queryParams` map into multiple instance vars for each param)
* `limit` and `fetchLimit` should be combined (same for `start` and `fetchOffset`)

**Comment by andrus** [comment]
This change was reverted. We'll approach it differently (see #309)
