### ISSUE TITLE
Refactoring the Pipeline to process explicit query parameters. 

### ISSUE THREAD

**Issue by vyarmolovich** [nhl/link-rest#312]
In scope of this should be implemented two additional stages: 
**ConvertQueryParamsStage** - for converting explicit query parameters and store they as query object in the context
**MergeQueryParamsStage** - for merging query parameters from rawQuery and query and store result as mergedQuery in the context

And as result both UriInfo and explicit query parameters should be processed.

**Comment by andrus** [comment]
Closing. Partially superseded by #309 .
