### ISSUE TITLE
Create protocol value object converters and providers.

### ISSUE THREAD

**Issue by vyarmolovich** [nhl/link-rest#321]
Create value object providers by implementing javax.ws.rs.ext.ParamConverterProvider.
Providers use converters based on javax.ws.rs.ext.ParamConverter. These converters should be implemented as well.

**Comment by andrus** [comment]
This feature is exciting as it allows to bind typed value objects explicitly as query parameters and analyze/amend them before they are passed down to the LinkRest chain.

```java
@GET
public DataResponse<X> get(@QueryParam("cayenneExp") CayenneExp cayenneExp) {
  
    // (not shown) analyze and change exp if needed...
	LrRequest request = LrRequest.builder().cayenneExp(cayenneExp).build();
    return LinkRest.select(E2.class, config).request(request).get();
}
```
