### ISSUE TITLE
Chain-of-responsibility execution pipeline

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#94]
There are lots of benefits in defining execution pipeline as a series of stages connected in a linked-list manner (chain-of-responsibility) :

* makes the execution stack explicit
* makes stages reusable
* allows various extensions to intercept / change / reroute individual stages

Specifically we are planning to implement stage listeners, and alternative POJO stacks. All these can take advantage of the new design. A stage in a chain looks like this: 

    public abstract class ProcessorStage<C extends ProcessorContext<?>> implements Processor<C> {
	   private Processor<C> next;

	public ProcessorStage(Processor<C> next) {
		this.next = next;
	}
	public void execute(C context) {
		// run our own processing, and then pass control down the chain...
		doExecute(context);
		if (next != null) {
			next.execute(context);
		}
	}
	protected abstract void doExecute(C context);  
    }

The important part is ProcessorContext - an object that will store the state between the stages.

**Comment by rzen** [comment]
thumbs up
